# Site settings
title: matt kaniaris.com
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kaniris.com" # the base hostname & protocol for your site
twitter_username:
github_username:  kans

# Build settings
markdown: kramdown
